os: linux
  dist: xenial

language: java
jdk: oraclejdk9

before_install:
  - chmod +x mvnw

script: - ./mvnw clean compile -B


# script: mvn package -DskipTests


# jobs:
#   include:
#     - stage: Test
#       script:
#         - ./mvnw clean install -B