version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  maven_build_and_test:
    docker:
      - image: maven

    working_directory: ~/product-import

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test   

workflows:
  version: 2
  maven_build_and_test:
    jobs:
      - maven_build_and_test:
          filters:
            branches:
              only: main
    # jobs:
    #   - maven/test # checkout, build, test, and upload test results